version: '3.9'

services:
  postgres:
    image: postgres:15.4
    pull_policy: never
    container_name: postgres_container
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "main_db"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      -  pgdata:/var/lib/postgresql/data/pgdata
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d main_db" ]
      interval: 180s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  postgres-main:
    image: postgres:15.4
    pull_policy: never
    container_name: postgres_main_container
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "master"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6432:5432"
    volumes:
      -  pgdata_main:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100

volumes:
  pgdata:
  pgdata_main:
