"""add table AI profile

Revision ID: 31e435e49606
Revises: 076dea7b5d3d
Create Date: 2025-05-06 22:47:47.607839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e435e49606'
down_revision: Union[str, None] = '076dea7b5d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_profiles',
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_profiles_id'), 'ai_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_profiles_id'), table_name='ai_profiles')
    op.drop_table('ai_profiles')
    # ### end Alembic commands ###
