"""add table_metadata

Revision ID: 766a1732b512
Revises: 2d99d079c3f8
Create Date: 2024-12-18 23:33:54.600902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766a1732b512'
down_revision: Union[str, None] = '2d99d079c3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables_metadata',
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('json_props', sa.JSON(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_metadata_id'), 'tables_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_metadata_id'), table_name='tables_metadata')
    op.drop_table('tables_metadata')
    # ### end Alembic commands ###
