"""remove useless id

Revision ID: bb45ba1e5833
Revises: 31e435e49606
Create Date: 2025-05-07 00:15:15.715142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb45ba1e5833'
down_revision: Union[str, None] = '31e435e49606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_profiles', 'connection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_profiles', sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
